import { useState, useEffect } from 'react';
import { collection, getDocs, query, orderBy, doc, updateDoc, onSnapshot, where, deleteDoc, writeBatch, getDoc, runTransaction, setDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { ApprovalRequest } from '../../types';
import { CheckCircle2, XCircle, Clock, Trash2, AlertTriangle } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { auth } from '../../lib/firebase';
import { handleFirestoreError, OperationType } from '../../lib/firestore-errors';
import ConfirmModal from '../../components/ConfirmModal';

export default function SuperAdminApprovals() {
  const { profile } = useAuth();
  const [approvals, setApprovals] = useState<ApprovalRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [confirmConfig, setConfirmConfig] = useState<{ isOpen: boolean; title: string; message: string; onConfirm: () => void; showCancel?: boolean } | null>(null);

  useEffect(() => {
    const unsubApprovals = onSnapshot(query(collection(db, 'approval_requests'), orderBy('requestedAt', 'desc')), (snap) => {
      setApprovals(snap.docs.map(d => ({ id: d.id, ...d.data() } as ApprovalRequest)));
      setLoading(false);
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, 'approval_requests', auth, profile);
      setLoading(false);
    });

    return () => unsubApprovals();
  }, [profile]);

  const handleApproval = async (request: ApprovalRequest, action: 'approve' | 'reject') => {
    try {
      const requestRef = doc(db, 'approval_requests', request.id);

      if (action === 'approve') {
        if (request.type === 'order_status' && request.orderId) {
          const orderRef = doc(db, 'orders', request.orderId);
          const orderSnap = await getDoc(orderRef);
          
          if (orderSnap.exists()) {
            const orderData = orderSnap.data();
            const oldStatus = orderData.status;
            const newStatus = request.targetStatus;

            await updateDoc(orderRef, { status: newStatus });
            
            const transQuery = query(
              collection(db, 'transactions'),
              where('orderNumber', '==', request.orderNumber)
            );
            
            const transSnap = await getDocs(transQuery);
            for (const tDoc of transSnap.docs) {
              const transStatus = newStatus === 'processing' ? 'pending' : newStatus;
              await updateDoc(doc(db, 'transactions', tDoc.id), { status: transStatus });
            }

            if (newStatus === 'cancelled' && oldStatus !== 'cancelled') {
              for (const item of orderData.items || []) {
                const productRef = doc(db, 'products', item.productId);
                await runTransaction(db, async (transaction) => {
                  const pDoc = await transaction.get(productRef);
                  if (!pDoc.exists()) return;
                  const currentStock = pDoc.data().stock || 0;
                  transaction.update(productRef, { stock: currentStock + item.quantity });
                });
              }
            } else if (oldStatus === 'cancelled' && newStatus !== 'cancelled') {
              for (const item of orderData.items || []) {
                const productRef = doc(db, 'products', item.productId);
                await runTransaction(db, async (transaction) => {
                  const pDoc = await transaction.get(productRef);
                  if (!pDoc.exists()) return;
                  const currentStock = pDoc.data().stock || 0;
                  const newStock = Math.max(0, currentStock - item.quantity);
                  transaction.update(productRef, { stock: newStock });
                });
              }
            }
          }
        } else if (request.type === 'daily_settlement_open' && request.closingId) {
          await deleteDoc(doc(db, 'dailyClosings', request.closingId));
          const charityQ = query(collection(db, 'charityRecords'), where('dailyClosingId', '==', request.closingId));
          const charitySnap = await getDocs(charityQ);
          for (const cDoc of charitySnap.docs) {
            await deleteDoc(doc(db, 'charityRecords', cDoc.id));
          }
          if (request.closingDate) {
            const dateObj = new Date(request.closingDate.seconds * 1000);
            const dateStr = dateObj.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
            const amalQuery = query(collection(db, 'transactions'), where('tenantId', '==', request.tenantId), where('type', '==', 'expense'), where('category', '==', 'Amal'), where('isAutoGenerated', '==', true));
            const amalSnap = await getDocs(amalQuery);
            for (const aDoc of amalSnap.docs) {
              if (aDoc.data().description.includes(dateStr)) {
                await deleteDoc(doc(db, 'transactions', aDoc.id));
              }
            }
          }
        } else if (request.type === 'charity_revision' && request.charityId) {
          await deleteDoc(doc(db, 'charityRecords', request.charityId));
          if (request.closingDate) {
            const dateObj = new Date(request.closingDate.seconds * 1000);
            const dateStr = dateObj.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
            const amalQuery = query(collection(db, 'transactions'), where('tenantId', '==', request.tenantId), where('type', '==', 'expense'), where('category', '==', 'Amal'), where('isAutoGenerated', '==', true));
            const amalSnap = await getDocs(amalQuery);
            for (const aDoc of amalSnap.docs) {
              if (aDoc.data().description.includes(dateStr)) {
                await deleteDoc(doc(db, 'transactions', aDoc.id));
              }
            }
          }
        } else if (request.type === 'target_revision' && request.targetMonth) {
          const targetId = `${request.tenantId}_${request.targetMonth}`;
          await setDoc(doc(db, 'sales_targets', targetId), { 
            isUnlocked: true,
            tenantId: request.tenantId,
            month: request.targetMonth
          }, { merge: true });
        }

        await deleteDoc(requestRef);
        setConfirmConfig({
          isOpen: true,
          title: 'Berhasil',
          message: 'Permintaan telah disetujui dan dihapus.',
          onConfirm: () => setConfirmConfig(null),
          showCancel: false
        });
      } else {
        await deleteDoc(requestRef);
        setConfirmConfig({
          isOpen: true,
          title: 'Berhasil',
          message: 'Permintaan telah ditolak dan dihapus.',
          onConfirm: () => setConfirmConfig(null),
          showCancel: false
        });
      }
    } catch (err) {
      console.error(err);
      handleFirestoreError(err, OperationType.UPDATE, `approval_requests/${request.id}`, auth, profile);
    }
  };

  const handleDeleteAllApprovals = async () => {
    setConfirmConfig({
      isOpen: true,
      title: 'HAPUS SEMUA APPROVAL',
      message: 'Apakah Anda yakin ingin menghapus SEMUA daftar permintaan persetujuan? Tindakan ini tidak dapat dibatalkan.',
      onConfirm: async () => {
        setConfirmConfig(null);
        try {
          const batch = writeBatch(db);
          approvals.forEach(req => {
            batch.delete(doc(db, 'approval_requests', req.id));
          });
          await batch.commit();
          setConfirmConfig({
            isOpen: true,
            title: 'Berhasil',
            message: 'Semua daftar persetujuan telah dihapus.',
            onConfirm: () => setConfirmConfig(null),
            showCancel: false
          });
        } catch (err) {
          console.error(err);
          handleFirestoreError(err, OperationType.DELETE, 'approval_requests_batch', auth, profile);
        }
      }
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Approval Requests</h2>
          <p className="text-gray-500">Manage requests from tenants to revert or change restricted data.</p>
        </div>
        {approvals.length > 0 && (
          <button
            onClick={handleDeleteAllApprovals}
            className="flex items-center px-4 py-2 bg-red-50 text-red-600 rounded-xl text-sm font-bold hover:bg-red-100 transition-all"
          >
            <Trash2 className="w-4 h-4 mr-2" />
            Hapus Semua List
          </button>
        )}
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
              <tr>
                <th className="px-6 py-4 font-medium">Tenant</th>
                <th className="px-6 py-4 font-medium">Type</th>
                <th className="px-6 py-4 font-medium">Reference</th>
                <th className="px-6 py-4 font-medium">Requested At</th>
                <th className="px-6 py-4 font-medium">Status</th>
                <th className="px-6 py-4 font-medium">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {loading ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500">Memuat data approval...</td>
                </tr>
              ) : approvals.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500">Tidak ada permintaan persetujuan.</td>
                </tr>
              ) : (
                approvals.map((request) => (
                  <tr key={request.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <p className="font-medium text-gray-900">{request.tenantName}</p>
                      <p className="text-xs text-gray-500">ID: {request.tenantId}</p>
                    </td>
                    <td className="px-6 py-4">
                      <span className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs font-medium">
                        {request.type === 'order_status' ? 'Status Order' : 
                         request.type === 'daily_settlement_open' ? 'Buka Tutup Buku' : 
                         request.type === 'charity_revision' ? 'Revisi Amal' : 
                         request.type === 'target_revision' ? 'Revisi Target' : request.type}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <p className="text-sm font-medium text-gray-900">{request.orderNumber || request.closingId || request.targetMonth || '-'}</p>
                      {request.targetStatus && (
                        <p className="text-xs text-indigo-600 font-bold">Target: {request.targetStatus}</p>
                      )}
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-500">
                      {request.requestedAt ? new Date(request.requestedAt.seconds * 1000).toLocaleString() : '-'}
                    </td>
                    <td className="px-6 py-4">
                      <span className="flex items-center text-amber-600 text-xs font-bold">
                        <Clock className="w-3 h-3 mr-1" />
                        PENDING
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex space-x-2">
                        <button
                          onClick={() => handleApproval(request, 'approve')}
                          className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                          title="Setujui"
                        >
                          <CheckCircle2 className="w-5 h-5" />
                        </button>
                        <button
                          onClick={() => handleApproval(request, 'reject')}
                          className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                          title="Tolak"
                        >
                          <XCircle className="w-5 h-5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {confirmConfig && (
        <ConfirmModal
          isOpen={confirmConfig.isOpen}
          title={confirmConfig.title}
          message={confirmConfig.message}
          onConfirm={confirmConfig.onConfirm}
          onCancel={() => setConfirmConfig(null)}
          showCancel={confirmConfig.showCancel}
        />
      )}
    </div>
  );
}
